import type { CreativeOption, CreativeCategory, DeviceId, Difficulty, SubstyleId } from "./types";

/**
 * Seed library of creative production options (15+ per category).
 * These are actionable production moves tailored to the
 * MPC Live III + Analog Rytm MKII + Analog Four MKII workflow.
 */

let _n = 0;
type Dev = DeviceId | "any";
type Fit = SubstyleId[] | "all";

function opt(
  category: CreativeCategory,
  title: string,
  recommendedDevice: Dev,
  difficulty: Difficulty,
  styleFit: Fit,
  description: string,
  whenToUse: string,
  implementationSteps: string[],
  variationIdeas: string[]
): CreativeOption {
  _n += 1;
  return {
    id: `${category}-${String(_n).padStart(3, "0")}`,
    category,
    title,
    description,
    recommendedDevice,
    difficulty,
    styleFit,
    whenToUse,
    implementationSteps,
    variationIdeas,
  };
}

/* ------------------------------------------------------------------ DRUMS */
const drums: CreativeOption[] = [
  opt("drums", "Sparse kick/snare with off-grid hat nudges", "rytm", "beginner", "all",
    "A minimal kick + snare backbone with hi-hats micro-nudged off the grid for a human pocket.",
    "When you want groove and space rather than busy programming.",
    ["Program kick on 1 and snare on 2 & 4 on the Rytm", "Add closed hats on 8ths", "Micro-time a few hats slightly late", "Sequence the master pattern from the MPC and mute/unmute Rytm tracks for variation"],
    ["Move a single hat early for a rushed feel", "Drop the kick on beat 3 occasionally", "Swap closed hats for open hats every 4th bar"]),
  opt("drums", "Sampled break under analog kick", "mpc", "intermediate", ["boom-bap","east-coast","soul-sample","grimy-underground","lofi"],
    "Layer a chopped vinyl break (MPC) with a punchy analog kick (Rytm) for weight + character.",
    "When the sampled drums lack low-end punch on their own.",
    ["Chop a break on the MPC and lay it across pads", "High-pass the break slightly", "Add a Rytm analog kick on the downbeats to reinforce", "Tune the Rytm kick to the break"],
    ["Replace just the break's snare with a Rytm clap", "Sidechain the break to the Rytm kick", "Reverse the break's last 16th into the bar"]),
  opt("drums", "Trap hat rolls & triplet ratchets", "mpc", "intermediate", ["trap","southern-bounce","dark-cinematic"],
    "Fast 32nd/triplet hi-hat rolls and ratchets programmed for energy and motion.",
    "When the beat needs forward momentum and trap energy.",
    ["Program steady hats, then add note-repeat rolls on the MPC", "Vary roll speed (1/16 → 1/32 → 1/48)", "Drop velocity on roll tails", "Use Rytm retrig as an alternate ratchet source"],
    ["Pan hat rolls across the stereo field", "Pitch the hats up during a roll", "Leave a 1-bar gap with no hats for contrast"]),
  opt("drums", "Boom-bap dusty swing groove", "mpc", "beginner", ["boom-bap","east-coast","soul-sample","lofi"],
    "Hard-swung 16ths with vinyl dust and slightly loose timing for that 90s head-nod.",
    "When you want classic boom-bap feel.",
    ["Set MPC swing to ~56–60%", "Program kick/snare with intentionally imperfect timing", "Add vinyl crackle layer", "Vary snare velocity for a played feel"],
    ["Add a ghost snare before the backbeat", "Flam the snare occasionally", "Drop swing to 54% for a tighter take"]),
  opt("drums", "Analog clap + snare layering", "rytm", "intermediate", "all",
    "Stack a Rytm analog clap with a snare for a fatter, wider backbeat.",
    "When the snare feels thin or narrow.",
    ["Design a clap on one Rytm track", "Design a snare on another", "Trigger both on 2 & 4", "Pan the clap slightly wide, keep snare centered"],
    ["Add short reverb to only the clap", "Delay-throw the clap on phrase ends", "Pitch the snare down for darkness"]),
  opt("drums", "Ghost-note hi-hat funk", "rytm", "advanced", ["west-coast","southern-bounce","soul-sample","minimalist-drum-machine"],
    "Low-velocity ghost hats and snares filling the gaps for a funky, breathing groove.",
    "When a static groove needs life and bounce.",
    ["Program main hats at full velocity", "Add ghost hats at ~30% velocity on off-16ths", "Use velocity-locked p-locks on the Rytm", "Add ghost snares before the backbeat"],
    ["Open a ghost hat into the backbeat", "Randomize ghost velocities", "Mute ghosts in the hook for contrast"]),
  opt("drums", "808-driven minimal kit", "rytm", "beginner", ["trap","southern-bounce","dark-cinematic"],
    "Tuned 808-style kick doing double duty as kick + bass, with snappy clap and sparse hats.",
    "When you want modern trap minimalism.",
    ["Tune the Rytm kick low and let it ring", "Add a snappy clap on beat 3", "Keep hats sparse with occasional rolls", "Let the kick carry the sub"],
    ["Pitch-glide the kick between notes", "Distort the kick for grit", "Add a rimshot accent on the and-of-3"]),
  opt("drums", "Half-time cinematic hits", "rytm", "beginner", ["dark-cinematic","trap","experimental"],
    "Massive, slow, reverbed kick and snare placed sparsely for a filmic half-time feel.",
    "When you want weight, drama, and space.",
    ["Place kick on 1, snare on 3 (half-time)", "Add long reverb to the snare", "Tune drums low and heavy", "Leave lots of empty space"],
    ["Add a sub-drop under the kick", "Reverse-reverb into the snare", "Double the snare an octave down"]),
  opt("drums", "Percussion-layer world textures", "mpc", "intermediate", ["experimental","southern-bounce","west-coast","dark-cinematic"],
    "Add congas, shakers, rims, or found percussion to enrich the groove beyond the kit.",
    "When the drums feel one-dimensional.",
    ["Sample or load percussion one-shots on the MPC", "Program a syncopated shaker/conga line", "Pan percussion off-center", "Keep levels supportive, not dominant"],
    ["Run percussion through a filter LFO", "Use the Rytm for a tuned tom run", "Swap percussion every 8 bars"]),
  opt("drums", "Glitch / broken beat programming", "mpc", "advanced", ["experimental","grimy-underground","lofi"],
    "Stutter edits, dropped steps, and broken patterns for an unstable, abstract groove.",
    "When you want experimental, non-grid drums.",
    ["Program a normal beat, then delete/displace random steps", "Add stutter retrigs on the MPC", "Resample and re-chop the drum loop", "Glitch only specific bars for contrast"],
    ["Bitcrush the broken section", "Reverse a stuttered hit", "Quantize-then-randomize for controlled chaos"]),
  opt("drums", "West Coast tight bounce kit", "rytm", "intermediate", ["west-coast","southern-bounce"],
    "Tight, punchy, clean kick/snare with crisp hats and a confident bounce.",
    "When you want clean G-funk-era drums.",
    ["Design a tight analog kick with short decay", "Crisp snare, minimal reverb", "Clean 8th/16th hats with light swing", "Keep everything punchy and dry"],
    ["Add a tambourine layer on the offbeats", "Open hat on the and-of-4", "Slightly swing the hats for bounce"]),
  opt("drums", "Lo-fi soft & wobbly drums", "rytm", "beginner", ["lofi","soul-sample"],
    "Low-velocity, detuned, slightly unstable drums with brush and rim textures.",
    "When you want cozy, imperfect lo-fi drums.",
    ["Lower overall velocities on the Rytm", "Detune the kick/snare slightly", "Add a rim or brush layer", "Apply gentle wow/flutter via the MPC after recording"],
    ["Randomize micro-timing for human drift", "Filter the whole kit with a low-pass", "Add a soft vinyl hiss bed"]),
  opt("drums", "Drum-machine mute performance", "rytm", "intermediate", ["minimalist-drum-machine","experimental","west-coast"],
    "Build a full pattern, then perform the arrangement by muting/unmuting Rytm tracks live.",
    "When the groove is the song and arrangement = subtraction.",
    ["Program a complete busy pattern on the Rytm", "Mute most tracks to start", "Unmute elements over time while recording into the MPC", "Capture the live mute performance as audio"],
    ["P-lock a filter on the kick during mutes", "Bring in hats last for a build", "Drop to kick-only before the hook"]),
  opt("drums", "Snare-on-3 modern bounce", "mpc", "beginner", ["trap","southern-bounce","dark-cinematic"],
    "Backbeat on beat 3 only (half-time) for a spacious modern pocket.",
    "When 2-and-4 feels too busy for the tempo.",
    ["Move the snare/clap to land on beat 3", "Let the kick fill 1 and syncopated spots", "Keep hats steady around it", "Feel it at half the BPM"],
    ["Add a ghost snare on the and-of-3", "Layer a clap with the snare", "Throw a delay on the snare into the next bar"]),
  opt("drums", "Polyrhythmic hat layering", "rytm", "advanced", ["experimental","minimalist-drum-machine","dark-cinematic"],
    "Overlay a 3-against-4 or 5-step hat pattern over a 4/4 kick for hypnotic motion.",
    "When you want subtle complexity and movement.",
    ["Set one Rytm track to a different step length (e.g. 3 or 5)", "Let it cycle against the 16-step kit", "Keep velocity low so it weaves", "Record a long pass to capture the phasing"],
    ["Pan the polyrhythmic hat", "P-lock pitch changes across its steps", "Add a second polymeter on percussion"]),
  opt("drums", "Trap-to-boom-bap beat switch", "mpc", "advanced", ["trap","experimental","dark-cinematic"],
    "Two contrasting drum feels in one track, switched at a key arrangement moment.",
    "When you want a dramatic 'beat switch' second half.",
    ["Build a trap pattern for section A", "Build a boom-bap pattern for section B", "Use MPC sequences/song mode to switch", "Bridge the switch with a transition fill"],
    ["Change BPM feel at the switch", "Keep the same bass to glue the halves", "Switch back for a final hook"]),
];

/* ------------------------------------------------------------------- BASS */
const bass: CreativeOption[] = [
  opt("bass", "Two-note minor bass with filter envelope", "a4", "beginner", "all",
    "A simple root-fifth or root-flat7 bass with A4 filter-envelope movement for life.",
    "When you want a moving, vocal bass without complex notes.",
    ["Pick the root note on the A4", "Add one supporting note (5th or b7)", "Dial a filter envelope for per-note movement", "Record the pattern into MPC verse/hook sections"],
    ["Add glide between the two notes", "Open the filter more in the hook", "Octave-jump the second note"]),
  opt("bass", "808 glide bass following the key", "a4", "intermediate", ["trap","southern-bounce","dark-cinematic"],
    "Pitched sub bass that glides between notes to match the melody, 808-style.",
    "When the track needs that modern sliding low end.",
    ["Tune the A4 to a sine-ish sub patch", "Enable portamento/glide", "Play root notes following the chord changes", "Set note length so glides connect"],
    ["Distort the 808 for grit", "Add a click transient layer from the Rytm", "Pitch-bend a fill at the end of the phrase"]),
  opt("bass", "Walking sample-style bass", "a4", "advanced", ["boom-bap","east-coast","soul-sample","west-coast"],
    "A walking bassline that moves between chord tones for a jazzy, sampled feel.",
    "When you want bass that implies the harmony, jazz-style.",
    ["Map the chord roots", "Connect them with passing notes on the A4", "Keep it locked to the kick rhythmically", "Use a warm, slightly muted tone"],
    ["Swing the bass notes with the drums", "Add a chromatic approach note", "Drop to roots-only in the hook for impact"]),
  opt("bass", "Sub reinforcement under sample", "a4", "beginner", "all",
    "A clean sine sub doubling the root of your sample/chords to add weight.",
    "When a sampled loop lacks low-end on club systems.",
    ["Identify the root note of the loop", "Play a clean sub on the A4 matching it", "High-pass the sample so the sub owns the lows", "Keep it simple — one note per chord"],
    ["Follow chord changes with the sub", "Sidechain the sub to the kick", "Add subtle saturation for presence"]),
  opt("bass", "Syncopated funk bass", "a4", "advanced", ["west-coast","southern-bounce","soul-sample"],
    "A bouncy, syncopated bass with ghost notes and slides for funk energy.",
    "When you want groove-forward, danceable bass.",
    ["Write a syncopated rhythm off the kick", "Add muted ghost notes between hits", "Use slides into accented notes", "Keep the tone round and punchy"],
    ["Add a octave pop on the accent", "Mute-strum 16ths for a percussive feel", "Simplify in the verse, bring funk in the hook"]),
  opt("bass", "Drone / sustained sub bed", "a4", "beginner", ["dark-cinematic","experimental","minimalist-drum-machine"],
    "A long, sustained sub drone that sits under everything for ominous weight.",
    "When you want tension and a huge low foundation.",
    ["Hold a single low root on the A4", "Add very slow filter movement", "Layer subtle distortion or sub-octave", "Let it ring through the section"],
    ["Slowly detune for unease", "Add an LFO wobble", "Drop it out entirely for a 'floor falls away' moment"]),
  opt("bass", "Reese-style detuned bass", "a4", "advanced", ["experimental","grimy-underground","dark-cinematic"],
    "Stacked detuned saws creating a thick, gritty, moving bass texture.",
    "When you want an aggressive, modern, textured low end.",
    ["Stack/detune the A4 oscillators", "Add overdrive", "Sweep the filter for movement", "High-pass slightly so the kick fits"],
    ["Add slow LFO to the detune", "Resample and re-pitch for new tones", "Mono the lows, widen the highs"]),
  opt("bass", "Kick-locked one-note pulse", "a4", "beginner", ["minimalist-drum-machine","trap","grimy-underground"],
    "A single repeated bass note locked tightly to the kick for hypnotic drive.",
    "When less is more and you want pure groove.",
    ["Pick one root note", "Trigger it exactly with the kick", "Use a short, punchy envelope", "Let repetition build hypnosis"],
    ["Add an occasional octave jump", "Filter-open across 8 bars", "Drop every 4th hit for space"]),
  opt("bass", "Picked / fingered electric-bass tone", "a4", "intermediate", ["lofi","soul-sample","boom-bap","west-coast"],
    "A warm, plucky electric-bass-style tone with finger-style dynamics.",
    "When you want organic, musical bass for sample-based beats.",
    ["Design a plucky A4 patch with quick attack", "Add slight finger-noise via velocity", "Play a melodic line following the chords", "Warm it with chorus and gentle saturation"],
    ["Slide between two notes", "Add a dead/ghost note for groove", "Double an octave up softly in the hook"]),
  opt("bass", "Acid-style resonant bassline", "a4", "advanced", ["experimental","minimalist-drum-machine","grimy-underground"],
    "A squelchy, high-resonance bassline with accent and slide for movement.",
    "When you want a hypnotic, evolving 303-style line.",
    ["Write a 16-step line on the A4 sequencer", "Crank filter resonance", "Add slides and accents per step (p-locks)", "Modulate cutoff over time"],
    ["Automate resonance up across a build", "Distort for extra bite", "Alternate accent patterns each loop"]),
  opt("bass", "Half-time sub hits", "a4", "beginner", ["dark-cinematic","trap"],
    "Sparse, long sub notes hitting on the downbeats for cinematic weight.",
    "When the track is spacious and needs occasional massive low end.",
    ["Play long root notes on beats 1 (and 3)", "Use a pure sub tone", "Let each note fully sustain", "Tune to the track's key"],
    ["Add a slow pitch fall on release", "Layer a sub-drop sample", "Sidechain the pad to these hits"]),
  opt("bass", "Octave-bouncing bass", "a4", "intermediate", ["west-coast","southern-bounce","minimalist-drum-machine"],
    "Bass alternating between root and its octave for bouncy energy.",
    "When you want movement from one note.",
    ["Sequence root–octave–root–octave on the A4", "Accent the low octave", "Lock to the kick groove", "Keep the tone punchy"],
    ["Add swing to the octave bounce", "Filter the high octave brighter", "Throw in a fifth occasionally"]),
  opt("bass", "Distorted grime sub", "a4", "intermediate", ["grimy-underground","experimental","dark-cinematic"],
    "An overdriven, forward sub that growls and cuts through a raw mix.",
    "When you want aggressive, in-your-face low end.",
    ["Start with a sub patch on the A4", "Push the overdrive hard", "Shape with the filter to control mud", "Mono and high-pass slightly"],
    ["Add a bitcrush layer", "Resample the distortion to commit it", "Automate drive across sections"]),
  opt("bass", "Chord-tone arpeggiated bass", "a4", "advanced", ["soul-sample","west-coast","experimental"],
    "An arpeggio outlining the chord in the bass register for melodic motion.",
    "When you want the bass to carry harmony melodically.",
    ["Set the A4 arpeggiator to the chord", "Keep it in the low register", "Sync to tempo from the MPC", "Tame the highs with a filter"],
    ["Change arp direction per section", "Add octave range in the hook", "Gate it rhythmically against the kick"]),
  opt("bass", "Side-chained pumping sub", "a4", "intermediate", ["trap","southern-bounce","dark-cinematic","west-coast"],
    "A sub that ducks to the kick, creating a pumping, breathing low end.",
    "When kick and bass fight for the same space.",
    ["Use the A4's envelope/LFO or MPC sidechain to duck the sub", "Trigger ducking from the kick", "Set release to taste", "Check the low end on a sub speaker"],
    ["Pump the pad with the same trigger", "Exaggerate for an EDM-leaning feel", "Subtle duck for transparency"]),
];

/* --------------------------------------------------------------- CHORDS */
const chords: CreativeOption[] = [
  opt("chords", "Minor 7th / 9th lo-fi chords", "a4", "beginner", ["lofi","soul-sample","boom-bap","east-coast"],
    "Lush extended minor chords (m7, m9) for that jazzy, emotional hip-hop color.",
    "When you want warm, sophisticated harmony.",
    ["Build a minor 7th chord on the A4", "Add the 9th for richness", "Use a warm, detuned patch with chorus", "Play 2–4 chords in a loop"],
    ["Voice chords higher for a Rhodes feel", "Add slow filter swells", "Invert chords across the progression"]),
  opt("chords", "Four-chord minor loop with filter swells", "a4", "beginner", "all",
    "A repeating 4-chord minor progression with the filter slowly opening and closing.",
    "When you need an evergreen emotional backbone.",
    ["Pick 4 minor-key chords (i–VI–III–VII works)", "Loop them every bar or two", "Automate the A4 filter to breathe", "Layer a sub on the roots"],
    ["Add a passing diminished chord", "Change one chord in the hook", "Pulse the chords rhythmically"]),
  opt("chords", "Chopped soul-sample chords", "mpc", "intermediate", ["soul-sample","boom-bap","east-coast","lofi"],
    "Re-pitch chops of a soul/gospel sample into a new chord progression on the MPC.",
    "When you want authentic, complex sampled harmony.",
    ["Find a rich chord in a soul record", "Chop it and spread across MPC pads", "Re-pitch chops to build a progression", "Filter and EQ to fit the mix"],
    ["Reverse a chop for a swell", "Layer two samples for thickness", "Time-stretch a chop into a pad"]),
  opt("chords", "Dark cinematic minor pads", "a4", "intermediate", ["dark-cinematic","trap","experimental"],
    "Slow, ominous minor pads with dissonant tension for filmic mood.",
    "When you want tension and atmosphere over groove.",
    ["Build a dark minor chord on the A4", "Add a slow attack for a pad", "Introduce a dissonant tension note", "Drench in reverb"],
    ["Add a tritone for menace", "Slowly detune for unease", "Automate a swell into each section"]),
  opt("chords", "Stab-and-space comping", "a4", "intermediate", ["west-coast","southern-bounce","boom-bap"],
    "Short rhythmic chord stabs with lots of space between them for groove.",
    "When sustained chords clutter the mix.",
    ["Make a short, punchy A4 chord patch", "Play stabs on syncopated offbeats", "Leave silence between stabs", "Add a touch of delay on the stab"],
    ["Throw a stab into reverb on phrase ends", "Alternate two voicings", "Filter-down the stab in the verse"]),
  opt("chords", "Suspended / unresolved harmony", "a4", "advanced", ["experimental","dark-cinematic","lofi"],
    "Sus2/sus4 and unresolved voicings that float without a clear home.",
    "When you want a dreamy or uneasy, open feeling.",
    ["Replace the 3rd with a 2nd or 4th", "Loop without resolving to a tonic", "Use a soft, airy patch", "Let chords overlap slightly"],
    ["Resolve only at the hook", "Add a pedal tone underneath", "Pan a doubled voice wide"]),
  opt("chords", "Gospel-style passing chords", "a4", "advanced", ["soul-sample","west-coast","boom-bap"],
    "Rich passing and chromatic chords connecting the main harmony, gospel-influenced.",
    "When you want sophisticated, moving harmony.",
    ["Establish your main chords", "Insert chromatic passing chords between them", "Voice-lead smoothly (small movements)", "Use a warm electric-piano patch"],
    ["Add a walk-up into the hook chord", "Borrow a chord from the parallel major", "Drop to a single chord for contrast"]),
  opt("chords", "Detuned Rhodes electric-piano", "a4", "beginner", ["lofi","soul-sample","boom-bap"],
    "A warm, slightly detuned electric-piano sound for cozy, nostalgic chords.",
    "When you want that classic lo-fi keys vibe.",
    ["Design a Rhodes-like A4 patch", "Add slight detune and chorus", "Play soft, swung chords", "Add vinyl/tape character via the MPC"],
    ["Roll the chords (slight strum)", "Add tremolo", "Filter darker in the verse"]),
  opt("chords", "Single-note tonal motif (implied harmony)", "a4", "beginner", ["minimalist-drum-machine","trap","dark-cinematic","experimental"],
    "A single repeating melodic note/figure that implies the harmony without full chords.",
    "When full chords feel too busy or dense.",
    ["Pick one strong note in the key", "Repeat it rhythmically on the A4", "Let bass + melody imply the rest", "Add space and reverb"],
    ["Move the note every 4 bars", "Add an octave answer", "Pulse it with the hats"]),
  opt("chords", "Organ / brass stabs", "a4", "intermediate", ["southern-bounce","west-coast","soul-sample"],
    "Punchy organ or brass-style chord stabs for energetic, chantable hooks.",
    "When you want bold, danceable harmony.",
    ["Design a bright organ/brass A4 patch", "Play short rhythmic stabs", "Accent the hook with them", "Add a bit of room reverb"],
    ["Add a fall/doit on the last stab", "Harmonize a counter stab", "Filter-sweep them into the drop"]),
  opt("chords", "Wide pad bed under everything", "a4", "beginner", ["dark-cinematic","lofi","experimental"],
    "A soft, wide sustained pad that glues the whole track together subtly.",
    "When the mix feels disconnected or thin.",
    ["Build a soft, slow-attack A4 pad", "Play the root + a chord tone", "Keep the level low and supportive", "Widen with chorus/stereo"],
    ["Slowly evolve the filter over a section", "Swell it up into the hook", "Drop it in the breakdown for contrast"]),
  opt("chords", "Tritone / diminished tension chords", "a4", "advanced", ["dark-cinematic","experimental","grimy-underground"],
    "Diminished and tritone voicings for unstable, menacing harmony.",
    "When you want darkness and unresolved tension.",
    ["Build a diminished chord on the A4", "Use it as a tense passing or main chord", "Keep voicings tight and low-mid", "Don't resolve it"],
    ["Glide between two dim chords", "Layer a dissonant high note", "Use it only at transitions for shock"]),
  opt("chords", "Arpeggiated chord pattern", "a4", "intermediate", ["experimental","lofi","west-coast","minimalist-drum-machine"],
    "Break a chord into a rhythmic arpeggio for motion instead of block chords.",
    "When sustained chords feel static.",
    ["Set the A4 arp to your chord", "Sync to MPC tempo", "Choose an up/down/random pattern", "Add subtle filter movement"],
    ["Change arp rate in the hook", "Add a second octave range", "Gate the arp against the snare"]),
  opt("chords", "Two-chord hypnotic vamp", "a4", "beginner", ["trap","minimalist-drum-machine","dark-cinematic","grimy-underground"],
    "Just two chords trading back and forth for a hypnotic, modern loop.",
    "When you want simplicity and repetition to carry the track.",
    ["Pick two related minor chords", "Alternate them every 1–2 bars", "Use a simple, dark patch", "Let the groove and melody do the work"],
    ["Add a third chord only in the bridge", "Filter one chord darker", "Drop one chord out for tension"]),
  opt("chords", "Reversed chord swells", "mpc", "intermediate", ["lofi","dark-cinematic","experimental","soul-sample"],
    "Reverse the tail of a chord so it swells up into the downbeat.",
    "When you want smooth, atmospheric transitions into phrases.",
    ["Record a chord (A4 or sample)", "Reverse the audio in the MPC", "Time it to swell into beat 1", "Add reverb for smoothness"],
    ["Layer a forward chord on the hit", "Pitch the reverse up over its length", "Use only before the hook"]),
];

/* ------------------------------------------------------------- MELODY */
const melody: CreativeOption[] = [
  opt("melody", "Two-bar motif you can vary", "a4", "beginner", "all",
    "A short, memorable 2-bar melodic idea that becomes the seed for the whole track.",
    "When you need a hook foundation that's easy to develop.",
    ["Write a simple 2-bar phrase on the A4", "Make it singable", "Loop it to test memorability", "Capture into MPC hook section"],
    ["Transpose it for the verse", "Add a note in the repeat", "Answer it with a second phrase"]),
  opt("melody", "West Coast portamento lead", "a4", "intermediate", ["west-coast","southern-bounce"],
    "The signature whiny, gliding G-funk lead synth with heavy portamento.",
    "When you want that classic West Coast hook.",
    ["Design a bright saw lead on the A4", "Crank portamento/glide", "Play a melodic, sliding line", "Add light delay and a touch of chorus"],
    ["Vibrato on long notes", "Octave jump for the hook peak", "Harmonize a second lead line"]),
  opt("melody", "Dark trap bell melody", "a4", "intermediate", ["trap","dark-cinematic"],
    "An eerie bell/pluck melody in a minor key for modern trap mood.",
    "When you want a haunting, catchy trap lead.",
    ["Design a bell/pluck patch on the A4", "Write a sparse minor melody", "Add long reverb/delay tails", "Leave space between phrases"],
    ["Pitch a phrase up an octave", "Add a counter-pluck", "Stutter-edit a phrase end"]),
  opt("melody", "Chopped vocal-sample hook", "mpc", "intermediate", ["soul-sample","southern-bounce","trap","experimental"],
    "Chop a vocal phrase and rearrange it into a catchy, rhythmic hook on the MPC.",
    "When you want a vocal hook without recording vocals.",
    ["Find a vocal phrase to sample", "Chop it across MPC pads", "Rearrange chops into a new melody/rhythm", "Pitch and time-stretch to fit"],
    ["Pitch the vocal up for an energetic feel", "Add formant shift for character", "Stutter a single syllable"]),
  opt("melody", "Call-and-response between MPC and A4", "any", "intermediate", "all",
    "A sampled/chopped phrase (MPC) answered by an analog counter-melody (A4).",
    "When you want conversational, engaging melody.",
    ["Place a chopped phrase on the MPC", "Write an A4 answer in the gaps", "Make the two trade every 2 bars", "Pan them slightly apart"],
    ["Make the A4 answer echo then vary the MPC phrase", "Swap who leads in the hook", "Layer both at the climax"]),
  opt("melody", "Pentatonic improv lead", "a4", "beginner", ["west-coast","soul-sample","lofi"],
    "Stay in the minor pentatonic scale for easy, always-musical melodies.",
    "When you want to jam melodies without theory worry.",
    ["Set the A4 scale to minor pentatonic", "Improvise over the chords", "Record several takes into the MPC", "Comp the best phrases"],
    ["Add a blue note for grit", "Double the best phrase an octave up", "Quantize loosely to keep feel"]),
  opt("melody", "Single-note hook with rhythm focus", "a4", "beginner", ["trap","minimalist-drum-machine","grimy-underground"],
    "A hook built from one or two notes where the rhythm is the hook.",
    "When melody should be minimal and rhythmic.",
    ["Pick one or two notes", "Design a catchy rhythmic pattern", "Use a punchy pluck patch", "Let repetition make it stick"],
    ["Add an occasional pitch jump", "Gate it with the hats", "Filter-open it across the hook"]),
  opt("melody", "Counter-melody under the main hook", "a4", "advanced", ["soul-sample","west-coast","dark-cinematic"],
    "A secondary melodic line weaving beneath the main hook for depth.",
    "When the hook feels lonely or thin.",
    ["Establish the main hook", "Write a lower counter-line on the A4", "Keep it in the chord tones", "Pan it opposite the main hook"],
    ["Make the counter answer the hook", "Bring it forward in the second hook", "Harmonize it in thirds"]),
  opt("melody", "Pitched percussion melody", "rytm", "advanced", ["experimental","minimalist-drum-machine","southern-bounce"],
    "Tune a Rytm percussion voice across pitches to play a melodic line.",
    "When you want a unique, percussive melodic timbre.",
    ["Pick a tonal Rytm voice (e.g. a tom or synth)", "P-lock different pitches per step", "Write a simple line", "Add reverb for melodic sustain"],
    ["Run it through a delay for arps", "Layer with the A4 in unison", "Detune for an off-kilter feel"]),
  opt("melody", "Whistle / flute-style topline", "a4", "intermediate", ["southern-bounce","west-coast","trap"],
    "A bright, airy whistle or flute lead for a catchy, chantable topline.",
    "When you want an instantly memorable, vocal-like hook.",
    ["Design an airy sine/triangle lead on the A4", "Write a simple, catchy phrase", "Add vibrato and light reverb", "Keep it in a comfortable register"],
    ["Add grace-note slides", "Double an octave down softly", "Answer it with a pluck"]),
  opt("melody", "Minimal two-note ostinato", "a4", "beginner", ["minimalist-drum-machine","dark-cinematic","experimental","lofi"],
    "A hypnotic two-note repeating figure that anchors the track.",
    "When you want subtle, trance-like melodic motion.",
    ["Choose two notes a step or third apart", "Repeat them steadily on the A4", "Use slow filter movement for interest", "Let it run under everything"],
    ["Shift one note up after 8 bars", "Add a third note in the hook", "Pan-modulate it slowly"]),
  opt("melody", "Reversed melodic swell intro", "mpc", "intermediate", ["lofi","dark-cinematic","experimental"],
    "Start a phrase with a reversed melody swelling into the first downbeat.",
    "When you want an atmospheric melodic entrance.",
    ["Record a melodic phrase", "Reverse it in the MPC", "Time the swell to land on beat 1", "Crossfade into the forward melody"],
    ["Add rising pitch to the reverse", "Layer reverb that blooms", "Use it before each hook"]),
  opt("melody", "Octave-displaced melody", "a4", "advanced", ["experimental","west-coast","soul-sample"],
    "Take a simple melody and jump some notes up/down an octave for surprise.",
    "When a melody feels predictable.",
    ["Write a basic melodic line", "Displace 2–3 notes by an octave", "Smooth the jumps with glide if needed", "Keep the contour recognizable"],
    ["Displace different notes each loop", "Widen the range in the hook", "Harmonize the displaced note"]),
  opt("melody", "Bluesy minor-third bends", "a4", "intermediate", ["west-coast","soul-sample","boom-bap"],
    "Add expressive pitch bends around the minor third for soulful character.",
    "When you want a vocal, human lead feel.",
    ["Play a minor-pentatonic line on the A4", "Bend into the minor third", "Use pitch-bend or per-step p-locks", "Keep bends tasteful"],
    ["Slow-bend a long note", "Bend down for a sigh effect", "Add vibrato after the bend"]),
  opt("melody", "Layered unison lead (analog + sample)", "any", "advanced", ["dark-cinematic","west-coast","experimental"],
    "Double an A4 lead with a sampled instrument on the MPC for a thick hybrid tone.",
    "When you want a bigger, signature lead sound.",
    ["Write the lead on the A4", "Double it with a matching MPC sample", "Tune and time-align them", "Blend levels and pan slightly"],
    ["Detune the layers a few cents", "Filter one layer darker", "Mute the sample layer in the verse"]),
];

/* -------------------------------------------------------------- SAMPLES */
const samples: CreativeOption[] = [
  opt("samples", "Classic chop-and-rearrange flip", "mpc", "beginner", ["boom-bap","soul-sample","east-coast","lofi"],
    "Chop a sample across pads and replay it in a new order to create an original loop.",
    "When you want to flip a record into something new.",
    ["Load the sample into the MPC", "Slice it into transient chops", "Spread chops across pads", "Replay them in a fresh sequence"],
    ["Re-pitch some chops", "Skip beats for syncopation", "Reverse one chop for variation"]),
  opt("samples", "Filtered sample intro reveal", "mpc", "beginner", "all",
    "Start with a heavily filtered sample, then open the filter at the drop.",
    "When you want a satisfying intro-to-drop reveal.",
    ["Loop the sample on the MPC", "Low-pass it hard for the intro", "Automate the filter to open at the drop", "Bring drums in as it opens"],
    ["High-pass version for an outro", "Notch-sweep for movement", "Bitcrush the filtered version"]),
  opt("samples", "Time-stretch a chop into a pad", "mpc", "intermediate", ["lofi","dark-cinematic","experimental","soul-sample"],
    "Stretch a short sample chop into a long sustained pad/texture.",
    "When you want atmospheric texture from a sample.",
    ["Pick a tonal chop", "Extreme time-stretch it in the MPC", "Loop the stretched tail", "Filter and reverb to taste"],
    ["Pitch the stretched pad down", "Layer two stretches", "Automate the loop point for movement"]),
  opt("samples", "Vocal chop instrument", "mpc", "intermediate", ["trap","southern-bounce","soul-sample","experimental"],
    "Chop a vocal into a playable instrument across the pads for melodic hooks.",
    "When you want vocal melodies you can perform.",
    ["Isolate a clean vocal phrase", "Chop per syllable/note", "Map chops chromatically across pads", "Play new melodies with them"],
    ["Add formant shifting", "Pitch a chop up an octave", "Stutter a chop rhythmically"]),
  opt("samples", "Re-pitch chops into a melody", "mpc", "intermediate", ["soul-sample","boom-bap","lofi"],
    "Tune individual chops to different pitches to build a melodic progression.",
    "When you want melody and harmony straight from a sample.",
    ["Chop a sustained tone from a record", "Assign each pad a different pitch", "Play a melody/chord progression", "Match levels and tone"],
    ["Build a full chord from stacked chops", "Add a sub under the root chop", "Reverse for a swell"]),
  opt("samples", "Found-sound / foley percussion", "mpc", "beginner", ["experimental","lofi","minimalist-drum-machine"],
    "Sample everyday sounds and turn them into unique percussion or texture.",
    "When you want a signature, original sound palette.",
    ["Record foley (clicks, taps, objects)", "Trim and map to MPC pads", "Use as hats, snaps, or texture", "Process to sit in the mix"],
    ["Pitch foley into a tonal hit", "Layer foley under the snare", "Reverse a foley swell"]),
  opt("samples", "Drum break extraction", "mpc", "advanced", ["boom-bap","east-coast","grimy-underground","lofi"],
    "Pull a drum break from a record and chop it for a vintage groove.",
    "When you want authentic, dusty break drums.",
    ["Find a clean drum break", "Chop it into individual hits", "Rebuild your own pattern from the hits", "Layer a Rytm kick for punch"],
    ["Swing the chopped break", "Replace the snare hit only", "Resample the rebuilt break"]),
  opt("samples", "Texture / atmosphere sampling", "mpc", "beginner", ["dark-cinematic","lofi","experimental"],
    "Sample ambience (rain, vinyl, room tone, field recordings) for a sonic bed.",
    "When the track needs space and a sense of place.",
    ["Load an ambience sample", "Loop it quietly under the beat", "EQ it to leave room for the mix", "Automate level for movement"],
    ["Filter the ambience rhythmically", "Layer two atmospheres", "Bring it forward in the breakdown"]),
  opt("samples", "Stutter / glitch resample", "mpc", "advanced", ["experimental","grimy-underground","trap"],
    "Resample a phrase and chop/repeat it for stutter and glitch effects.",
    "When you want digital, broken textures and fills.",
    ["Record a phrase to a new MPC sample", "Chop it finely", "Program rapid retriggers/stutters", "Use as a transition or fill"],
    ["Pitch-ramp the stutter", "Bitcrush the resample", "Gate it against the beat"]),
  opt("samples", "One-shot key/chord sampling", "mpc", "beginner", ["soul-sample","boom-bap","lofi"],
    "Sample a single instrument note and play it chromatically as an instrument.",
    "When you want to play a real instrument's tone melodically.",
    ["Sample one clean note (key, guitar, horn)", "Map it chromatically on the MPC", "Set loop/decay for sustain", "Play melodies or chords"],
    ["Layer the velocity for dynamics", "Add vibrato via LFO", "Detune slightly for warmth"]),
  opt("samples", "Sample-and-hold rhythmic gate", "mpc", "intermediate", ["experimental","lofi","minimalist-drum-machine"],
    "Gate a sustained sample rhythmically so it pulses with the beat.",
    "When you want a static sample to become rhythmic.",
    ["Loop a sustained sample", "Program a rhythmic mute/gate pattern", "Sync the gate to the tempo", "Smooth edges with a short fade"],
    ["Sync the gate to the hats", "Pan the gated pulses", "Vary the gate pattern per section"]),
  opt("samples", "Pitched-down 'screwed' sample", "mpc", "beginner", ["southern-bounce","dark-cinematic","experimental","grimy-underground"],
    "Pitch a sample way down for a slow, heavy, chopped-and-screwed vibe.",
    "When you want a dark, syrupy southern feel.",
    ["Load a vocal or melodic sample", "Pitch it down significantly", "Keep the tempo, lower the pitch", "Add slight time-stretch artifacts for grit"],
    ["Half-time the whole beat to match", "Add a slow phaser", "Reverse a pitched-down tail"]),
  opt("samples", "Layered multi-sample chord", "mpc", "advanced", ["soul-sample","dark-cinematic","lofi"],
    "Stack chops from multiple records to build a rich composite chord.",
    "When a single sample's chord isn't full enough.",
    ["Find chord tones across different samples", "Tune them to one key", "Stack on a single pad/sequence", "EQ each layer to fit"],
    ["Add a synth sub from the A4", "Pan the layers across the field", "Filter the stack as one for movement"]),
  opt("samples", "Reversed sample tail transition", "mpc", "beginner", ["lofi","dark-cinematic","soul-sample","experimental"],
    "Reverse the tail of a sample to swell into the next section.",
    "When you need a smooth, atmospheric transition.",
    ["Grab a sample's tail/reverb", "Reverse it in the MPC", "Place it in the bar before a change", "Time the peak to the downbeat"],
    ["Add rising pitch", "Layer with a snare roll", "Pan-sweep the reverse"]),
  opt("samples", "Micro-loop / 1-bar earworm", "mpc", "intermediate", ["lofi","minimalist-drum-machine","experimental"],
    "Loop a tiny 1-bar (or shorter) snippet to create a hypnotic earworm.",
    "When repetition and groove are the goal.",
    ["Find a compelling 1-bar phrase", "Loop it tightly", "Layer drums and bass under it", "Let small variations carry interest"],
    ["Shorten to a half-bar loop", "Filter it slowly over time", "Add a fill every 8 bars"]),
];

/* -------------------------------------------------------------- TEXTURE */
const texture: CreativeOption[] = [
  opt("texture", "Vinyl crackle & noise bed", "mpc", "beginner", ["lofi","boom-bap","soul-sample","east-coast"],
    "A continuous vinyl crackle/hiss layer for warmth and analog character.",
    "When the beat feels too clean or digital.",
    ["Load a vinyl-crackle sample on the MPC", "Loop it under the whole beat", "Set a low, supportive level", "EQ out any harshness"],
    ["Duck the crackle to the kick", "Bring it up in quiet sections", "Layer tape hiss with it"]),
  opt("texture", "Slow-evolving A4 pad drone", "a4", "beginner", ["dark-cinematic","lofi","experimental","minimalist-drum-machine"],
    "A subtle background drone whose filter/timbre evolves slowly over time.",
    "When you want depth and a sense of motion under static parts.",
    ["Build a soft drone on the A4", "Add a very slow LFO to the filter", "Keep level low and wide", "Let it shift across the section"],
    ["Detune slowly for unease", "Add an occasional swell", "Pan-modulate it gently"]),
  opt("texture", "Reversed cymbal / chord swells", "rytm", "beginner", "all",
    "Reverse cymbals or chord tails to swell into downbeats and phrases.",
    "When transitions feel abrupt or sections need lift.",
    ["Record/sample a cymbal or chord", "Reverse it", "Place before key downbeats", "Add reverb for smoothness"],
    ["Stack two reverses at different lengths", "Pitch-rise the reverse", "Use the Rytm's cymbal voice reversed"]),
  opt("texture", "Background foley movement", "mpc", "intermediate", ["lofi","experimental","dark-cinematic"],
    "Quiet foley (rain, birds, café, room tone) that adds life and space.",
    "When you want an immersive, lived-in atmosphere.",
    ["Choose ambience that fits the mood", "Loop it very quietly", "High-pass to avoid mud", "Automate small level changes"],
    ["Pan the ambience wide", "Swap atmospheres per section", "Feature it solo in the intro"]),
  opt("texture", "Rytm parameter-lock hat evolution", "rytm", "intermediate", ["minimalist-drum-machine","experimental","trap"],
    "Use p-locks to change hat pitch/decay/filter per step for an ever-evolving texture.",
    "When static hats feel lifeless.",
    ["Program a hat pattern on the Rytm", "P-lock pitch on some steps", "P-lock decay/filter on others", "Let the pattern breathe and morph"],
    ["P-lock reverb send on accents", "Randomize a few locks", "Automate the locks across sections"]),
  opt("texture", "Granular cloud from a chop", "mpc", "advanced", ["experimental","dark-cinematic","lofi"],
    "Granularize a sample into a shimmering cloud of texture.",
    "When you want abstract, evolving atmosphere.",
    ["Pick a tonal sample", "Apply granular/extreme stretch on the MPC", "Loop the resulting cloud", "Filter and reverb it"],
    ["Modulate grain position", "Pitch-shift the cloud", "Gate it rhythmically"]),
  opt("texture", "Sub-drop & riser pair", "a4", "beginner", ["trap","dark-cinematic","southern-bounce"],
    "A riser into the drop plus a sub-drop on the impact for cinematic weight.",
    "When you want big, satisfying section impacts.",
    ["Make a rising noise/pitch on the A4", "Place it in the bar before the drop", "Add a sub-drop (downward pitch) on the hit", "Balance levels so it's felt, not muddy"],
    ["Layer a reverse cymbal with the riser", "Automate filter up with the riser", "Double the sub-drop an octave down"]),
  opt("texture", "Tape wow & flutter wobble", "mpc", "beginner", ["lofi","soul-sample","experimental"],
    "Apply pitch wobble (wow/flutter) for a warped, nostalgic analog feel.",
    "When you want lo-fi imperfection and warmth.",
    ["Route the beat/sample through a tape/wow effect", "Set a subtle pitch modulation", "Apply to the sample or whole bus", "Resample to commit"],
    ["Increase flutter for a broken-tape feel", "Modulate only the sample", "Automate wobble depth"]),
  opt("texture", "Whitenoise sweep risers", "a4", "beginner", ["trap","southern-bounce","dark-cinematic","west-coast"],
    "Filtered white-noise sweeps that rise into sections for energy.",
    "When transitions need momentum.",
    ["Use noise on the A4", "Automate a band-pass filter to sweep up", "Time it to peak at the section change", "Add reverb tail"],
    ["Sweep down for a fall", "Pan the sweep across the field", "Layer with a snare roll"]),
  opt("texture", "Bitcrushed ear-candy blips", "mpc", "intermediate", ["experimental","lofi","grimy-underground","minimalist-drum-machine"],
    "Tiny bitcrushed/glitchy sounds that appear occasionally for interest.",
    "When the beat needs sparse, surprising details.",
    ["Create small blips/clicks", "Bitcrush them", "Place every 4–8 bars in gaps", "Pan them off-center"],
    ["Pitch-randomize each occurrence", "Delay-throw a blip", "Cluster a few as a fill"]),
  opt("texture", "Reverb-wash send layer", "any", "beginner", "all",
    "Send elements to a long reverb to create a unifying atmospheric wash.",
    "When the mix feels dry and disconnected.",
    ["Set up a long reverb send (MPC or A4 FX track)", "Send chords/leads/snare to it", "Blend the wash low", "EQ the wash to avoid mud"],
    ["Automate the send up in the breakdown", "Freeze the reverb for a wash drone", "Gate the reverb for rhythm"]),
  opt("texture", "Dub-style delay throws", "rytm", "intermediate", ["dark-cinematic","experimental","grimy-underground","southern-bounce"],
    "Throw single hits into a feedback delay for spiraling dub textures.",
    "When you want dynamic, performed texture.",
    ["Set a tempo-synced delay with feedback", "Send a snare/clap/vocal momentarily", "Perform the throws at phrase ends", "Filter the delay tail"],
    ["Increase feedback for a spiral", "Pitch the delay tail", "Throw on the last bar of every 8"]),
  opt("texture", "Field-recorded transient layer", "mpc", "intermediate", ["lofi","experimental","boom-bap"],
    "Layer subtle real-world transients (door, click, tap) for organic texture.",
    "When drums feel sterile.",
    ["Record small transient sounds", "Layer them under hats/snare", "Keep them subtle", "Time them tightly to the groove"],
    ["Pitch the transient to the key", "Pan it opposite the hats", "Use it as a ghost note"]),
  opt("texture", "Modulated stereo width pad", "a4", "advanced", ["dark-cinematic","west-coast","experimental"],
    "A pad with slowly modulating stereo width for a living, breathing image.",
    "When the stereo field feels static.",
    ["Build a wide A4 pad", "Modulate width/pan slowly", "Keep the lows mono", "Blend subtly behind the mix"],
    ["Automate width to widen at the hook", "Add chorus for shimmer", "Collapse to mono in the verse"]),
  opt("texture", "Rhythmic gated noise hat-alt", "a4", "intermediate", ["minimalist-drum-machine","experimental","trap"],
    "Gate analog noise rhythmically as an alternative hi-hat/texture layer.",
    "When you want an unconventional percussion texture.",
    ["Generate noise on the A4", "Gate it with a fast envelope per step", "Sync to the hat rhythm", "Filter to taste (closed vs open)"],
    ["Vary the gate length per step", "Pitch the filter for tonality", "Pan against the main hats"]),
];

/* -------------------------------------------------------------- EFFECTS */
const effects: CreativeOption[] = [
  opt("effects", "One cohesive reverb space", "mpc", "beginner", "all",
    "Pick a single reverb character for the whole beat to glue elements into one room.",
    "When elements sound like they're in different spaces.",
    ["Choose one reverb (room/plate/hall)", "Send multiple elements to it", "Vary send amounts, not reverbs", "EQ the return to avoid mud"],
    ["Automate the send in breakdowns", "Add a second short reverb for drums", "Duck the reverb to the kick"]),
  opt("effects", "Snare delay throw on phrase ends", "rytm", "beginner", "all",
    "Throw the snare into a tempo-synced delay on the last beat of a phrase.",
    "When transitions feel flat.",
    ["Set a 1/4 or 1/8 dotted delay", "Send the snare only on the last hit", "Use Rytm performance/p-lock to trigger the send", "Filter the delay tail"],
    ["Increase feedback for a longer throw", "Pitch the throw up", "Throw the clap instead"]),
  opt("effects", "Analog drive on the drum bus", "rytm", "beginner", ["boom-bap","grimy-underground","east-coast","trap"],
    "Push the Rytm's analog overdrive on the drum bus for punch and grit.",
    "When drums lack weight or attitude.",
    ["Send drums through the Rytm's drive", "Push to taste", "Compensate level", "Resample if committing"],
    ["Drive only the kick/snare", "Add distortion for grime", "Automate drive up in the hook"]),
  opt("effects", "Sidechain pump to the kick", "any", "intermediate", ["trap","southern-bounce","west-coast","dark-cinematic"],
    "Duck bass/pads/chords to the kick for a clean, pumping low end.",
    "When the kick and sustained elements clash.",
    ["Set a sidechain trigger from the kick", "Duck the bass and pad", "Set release for a musical pump", "Check on a sub system"],
    ["Exaggerate for an obvious pump", "Subtle duck for transparency", "Pump only the pad, not the bass"]),
  opt("effects", "Bitcrush / sample-rate reduction", "mpc", "beginner", ["lofi","experimental","grimy-underground"],
    "Reduce bit depth/sample rate for a crunchy, lo-fi, digital texture.",
    "When you want gritty, degraded character.",
    ["Apply bitcrush to a sample or bus", "Dial bit depth and sample rate", "Blend with the dry signal", "Resample to commit"],
    ["Crush only the drums", "Automate crush in the breakdown", "Crush a reverb return"]),
  opt("effects", "Filter automation movement", "a4", "beginner", "all",
    "Automate a low-pass filter opening/closing across a section for energy curves.",
    "When sections feel static in energy.",
    ["Pick the element (chords/sample/bus)", "Automate the filter over 8–16 bars", "Open into the hook, close in the verse", "Add resonance for character"],
    ["Sweep up into the drop", "LFO the filter for wobble", "Notch-sweep for movement"]),
  opt("effects", "Tape saturation warmth", "mpc", "beginner", ["lofi","soul-sample","boom-bap","west-coast"],
    "Add gentle tape-style saturation for analog warmth and glue.",
    "When a digital mix feels cold or harsh.",
    ["Apply tape/saturation to the bus", "Keep it subtle", "Tame highs that get harsh", "Check the low end stays tight"],
    ["Saturate the sample harder", "Add wow/flutter with it", "Drive the master bus lightly"]),
  opt("effects", "Auto-pan / tremolo movement", "a4", "intermediate", ["experimental","lofi","dark-cinematic","west-coast"],
    "Use tempo-synced auto-pan or tremolo to animate a static element.",
    "When a sustained sound needs motion.",
    ["Apply auto-pan/tremolo on the A4 element", "Sync rate to tempo", "Set depth to taste", "Keep the lows centered"],
    ["Pan the lead, tremolo the pad", "Increase depth into the hook", "Triplet-rate for a different feel"]),
  opt("effects", "Phaser / flanger sweep", "a4", "intermediate", ["west-coast","experimental","lofi","grimy-underground"],
    "A slow phaser/flanger for psychedelic movement on chords or the whole beat.",
    "When you want trippy, evolving motion.",
    ["Apply phaser/flanger on the A4 FX or a chord", "Set a slow rate", "Blend depth to taste", "Sync to tempo if possible"],
    ["Sweep it manually at a transition", "Flange the drum bus briefly", "Automate feedback for intensity"]),
  opt("effects", "Multiband / surgical EQ carving", "any", "advanced", "all",
    "Carve frequency space so each element has its own pocket.",
    "When the mix is muddy or elements mask each other.",
    ["High-pass non-bass elements", "Notch competing mids", "Boost each element's signature band lightly", "Reference an A/B track"],
    ["Dynamic-EQ the mud band", "Carve the pad around the vocal/lead", "Tilt-EQ the whole bus to taste"]),
  opt("effects", "Reverb freeze / shimmer drone", "a4", "advanced", ["dark-cinematic","experimental","lofi"],
    "Freeze a reverb tail into a sustained drone for ambient texture.",
    "When you want an evolving atmospheric pad from FX.",
    ["Send a chord into a long/freeze reverb", "Freeze the tail", "Layer it under the beat", "Filter and pan the drone"],
    ["Pitch-shift the shimmer up an octave", "Modulate the freeze filter", "Bring it up in the breakdown"]),
  opt("effects", "Distortion on the 808/sub", "a4", "intermediate", ["trap","grimy-underground","dark-cinematic","southern-bounce"],
    "Add controlled distortion to the sub so it reads on small speakers.",
    "When the 808 disappears on phones/laptops.",
    ["Duplicate or parallel the sub", "Distort the parallel copy", "High-pass the distorted layer", "Blend so lows stay clean but mids cut"],
    ["Automate distortion per section", "Use a soft-clip vs hard-clip", "Resample to commit the tone"]),
  opt("effects", "Telephone / band-pass intro effect", "mpc", "beginner", ["lofi","soul-sample","dark-cinematic","experimental"],
    "Band-pass the whole beat in the intro/breakdown, then open up for contrast.",
    "When you want a dramatic full-range reveal.",
    ["Band-pass the master/bus for the intro", "Run a bar or two", "Open to full range at the drop", "Add a transition swell"],
    ["Use it for an outro fade", "Automate the band narrowing", "Apply only to drums for a radio feel"]),
  opt("effects", "Gated reverb on the snare", "rytm", "intermediate", ["dark-cinematic","trap","west-coast"],
    "A big reverb cut short by a gate for a punchy, 80s-style snare.",
    "When you want a huge but tight snare.",
    ["Add a large reverb to the snare", "Gate it to cut the tail short", "Tune gate time to the tempo", "Balance dry/wet"],
    ["Lengthen the gate in the hook", "Apply to the clap instead", "Trigger the gate from the hats"]),
  opt("effects", "Stutter / glitch FX fill", "mpc", "advanced", ["experimental","trap","grimy-underground"],
    "Use a beat-repeat/stutter effect as a fill into a section change.",
    "When you want a digital, energetic transition.",
    ["Set a beat-repeat/stutter effect", "Engage it on the last 1–2 beats of a phrase", "Vary repeat rate for a build", "Release into the new section"],
    ["Pitch-ramp the stutter", "Bitcrush the stutter", "Gate it for rhythm"]),
];

/* ----------------------------------------------------------- TRANSITION */
const transition: CreativeOption[] = [
  opt("transition", "Snare-roll build into the hook", "rytm", "beginner", "all",
    "A snare/clap roll that accelerates into the next section for momentum.",
    "When you need energy lifting into a hook or drop.",
    ["Program a snare roll on the Rytm", "Accelerate it over the last bar (1/8→1/16→1/32)", "Crescendo the velocity", "Land hard on the downbeat"],
    ["Add a riser under the roll", "Pitch the roll up", "Cut to silence right before the hit"]),
  opt("transition", "Silence before the drop", "mpc", "beginner", "all",
    "Cut everything for a beat (or a bar) before the drop for maximum impact.",
    "When a drop needs to hit harder.",
    ["Mute all tracks for the last beat/bar", "Optionally leave one reverse swell", "Hit the drop full and hard", "Use MPC mute automation"],
    ["Leave only a vocal/lead in the gap", "Add a tape-stop into the silence", "Half the silence for a shorter tease"]),
  opt("transition", "Riser + sub-drop combo", "a4", "intermediate", ["trap","dark-cinematic","southern-bounce"],
    "A rising sweep into the change plus a downward sub-drop on the impact.",
    "When you want cinematic, satisfying section changes.",
    ["Build a noise/pitch riser on the A4", "Place it in the bar before the change", "Add a sub-drop on the downbeat", "Balance so it's felt not muddy"],
    ["Layer a reverse cymbal", "Automate filter up with the riser", "Double the sub-drop low"]),
  opt("transition", "Filter sweep up into chorus", "any", "beginner", "all",
    "Sweep a low-pass filter open across the whole mix into the hook.",
    "When you want a smooth energy lift.",
    ["Automate a master/bus low-pass", "Close it in the build, open at the hook", "Add resonance for drama", "Time the peak to the downbeat"],
    ["High-pass sweep for a different feel", "Combine with a riser", "Sweep down for an outro"]),
  opt("transition", "Reverse cymbal / chord swell", "rytm", "beginner", "all",
    "A reversed cymbal or chord swelling up into the downbeat.",
    "When transitions feel abrupt.",
    ["Reverse a cymbal/chord", "Place it before the change", "Time the peak to beat 1", "Add reverb for smoothness"],
    ["Stack two lengths", "Pitch-rise the reverse", "Pan-sweep it across"]),
  opt("transition", "Drum fill / break turnaround", "rytm", "intermediate", ["boom-bap","east-coast","west-coast","soul-sample"],
    "A classic drum fill or 1-bar break to turn the beat around into a new section.",
    "When you want a musical, human transition.",
    ["Program a tom/snare fill on the Rytm", "Place it in the last bar of the phrase", "Vary it from the main groove", "Land cleanly on the downbeat"],
    ["Drop to drums-only for the fill", "Add a flam or roll", "Throw the fill into a delay"]),
  opt("transition", "Tape-stop / pitch-down stop", "mpc", "intermediate", ["experimental","lofi","grimy-underground","southern-bounce"],
    "A tape-stop effect slowing the beat to a halt before a change.",
    "When you want a dramatic, gritty stop.",
    ["Apply a tape-stop on the bus", "Trigger it on the last beat", "Let it slow to silence", "Hit the new section fresh"],
    ["Speed-up version (tape-start)", "Pitch-down only the sample", "Glitch it instead of a clean stop"]),
  opt("transition", "Beat-switch transition", "mpc", "advanced", ["trap","experimental","dark-cinematic"],
    "Switch to a contrasting beat/feel at a key moment, bridged by a transition.",
    "When you want a dramatic second-half change.",
    ["Prepare the second beat in the MPC", "Use a fill/silence/vocal to bridge", "Switch sequences cleanly", "Keep one element constant to connect"],
    ["Change BPM feel at the switch", "Switch back for the final hook", "Layer both beats for one bar"]),
  opt("transition", "Downlifter into the verse", "a4", "intermediate", ["dark-cinematic","trap","experimental"],
    "A descending pitch/filter sweep to bring energy DOWN into a verse.",
    "When you want to relax energy after a hook.",
    ["Build a falling sweep on the A4", "Place it leaving the hook", "Lower the filter/energy", "Settle into the verse groove"],
    ["Add a sub-drop", "Reverse-reverb tail", "Filter the whole mix down briefly"]),
  opt("transition", "Vocal / sample stutter lead-in", "mpc", "intermediate", ["southern-bounce","trap","experimental","soul-sample"],
    "Stutter a vocal or sample chop to lead into a new section.",
    "When you want a vocal-driven transition.",
    ["Pick a vocal/sample chop", "Stutter/repeat it over the last beat", "Accelerate the repeats", "Release into the section"],
    ["Pitch-ramp the stutter", "Add delay on release", "Gate it to the beat"]),
  opt("transition", "Mute-drop breakdown", "rytm", "beginner", ["minimalist-drum-machine","west-coast","boom-bap","lofi"],
    "Strip back to one or two elements for a breakdown, then rebuild.",
    "When the track needs a dynamic dip and rebuild.",
    ["Mute most tracks for 4–8 bars", "Leave a key element (bass or chords)", "Rebuild elements one at a time", "Use MPC mute automation"],
    ["Drop to drums-only", "Add a new element on the rebuild", "Filter the remaining element"]),
  opt("transition", "Impact hit on the downbeat", "rytm", "beginner", ["dark-cinematic","trap","southern-bounce"],
    "A big cinematic impact/boom on the first beat of a new section.",
    "When section starts need weight.",
    ["Design/sample an impact hit", "Place it on the new section's beat 1", "Add reverb for size", "Tune it to the key"],
    ["Layer a sub-drop", "Reverse-swell into it", "Use a crash with it"]),
  opt("transition", "Drum-only bar before the hook", "rytm", "beginner", "all",
    "Drop everything but drums for one bar to spotlight the groove before the hook.",
    "When you want a punchy, classic turnaround.",
    ["Mute melodic elements for 1 bar", "Let the drums (maybe a fill) carry it", "Bring everything back on the hook", "Use MPC automation"],
    ["Add a fill in that bar", "Keep the bass too", "Throw a delay on the last snare"]),
  opt("transition", "Crescendo riser layer stack", "a4", "advanced", ["trap","dark-cinematic","southern-bounce"],
    "Stack multiple risers (noise, pitch, drum roll) for a massive build.",
    "When you want the biggest possible lift into a drop.",
    ["Layer a noise riser, pitch riser, and snare roll", "Crescendo all together", "Automate filters opening", "Cut to silence then hit the drop"],
    ["Add a reverse cymbal on top", "Pitch-bend the whole mix up", "Extend the build over 8 bars"]),
  opt("transition", "Half-time / double-time flip", "mpc", "advanced", ["trap","experimental","southern-bounce"],
    "Flip the drums to half- or double-time briefly as a transition device.",
    "When you want a rhythmic surprise into a section.",
    ["Reprogram the drums to half/double-time for a bar", "Keep the bass/melody constant", "Use it as the transition bar", "Resolve to the normal feel"],
    ["Half-time the whole hook", "Double-time only the hats", "Switch feel at the beat-switch"]),
];

/* ---------------------------------------------------------- ARRANGEMENT */
const arrangement: CreativeOption[] = [
  opt("arrangement", "Drums+bass verse → add chords in hook", "mpc", "beginner", "all",
    "Keep verses to drums and bass; introduce chords/lead in the hook for contrast.",
    "When you want clear energy contrast between sections.",
    ["Build the verse with drums + bass only", "Add chords/lead for the hook", "Use MPC mutes to switch", "Repeat for verse 2"],
    ["Add a counter-melody in hook 2", "Strip the hook to chords-only once", "Bring the lead into verse 2"]),
  opt("arrangement", "8-bar intro that strips to one element", "mpc", "beginner", "all",
    "Open with a single element (sample/chords) for 8 bars, then build the beat.",
    "When you want an inviting, gradual intro.",
    ["Pick one element for the intro", "Run it 8 bars", "Add drums at bar 5 or 9", "Reveal the full beat at the hook"],
    ["Filter the intro element", "Add vinyl/ambience under it", "Drop a fill before the beat enters"]),
  opt("arrangement", "Hook-first (top-loaded) structure", "mpc", "intermediate", ["trap","southern-bounce","west-coast"],
    "Lead with the hook to grab attention immediately, common in modern hip-hop.",
    "When the hook is the strongest part and needs front placement.",
    ["Start with a short hook", "Drop to the verse", "Return to the hook", "End on a final extended hook"],
    ["Tease the hook melody in the intro", "Vary the final hook", "Add an outro tag"]),
  opt("arrangement", "Subtractive mute-based arrangement", "rytm", "intermediate", ["minimalist-drum-machine","west-coast","experimental","lofi"],
    "Build a full pattern, then arrange the song by muting/unmuting parts live.",
    "When the groove is the song and you want a hardware-performance flow.",
    ["Program a complete pattern on all devices", "Mute most to start", "Unmute elements over time", "Record the mute performance into the MPC"],
    ["Drop to kick-only mid-song", "Bring hats in last", "Automate a filter during mutes"]),
  opt("arrangement", "Classic verse/hook/verse/hook/bridge/hook", "mpc", "beginner", ["west-coast","east-coast","soul-sample","southern-bounce"],
    "A song-form arrangement with a contrasting bridge for a complete track.",
    "When you want a full, vocal-ready song structure.",
    ["Map intro–V1–H–V2–H–bridge–H–outro", "Set section lengths (8/8/8...)", "Differentiate the bridge harmonically", "Build energy to the final hook"],
    ["Double the final hook", "Add a pre-hook lift", "Breakdown before the bridge"]),
  opt("arrangement", "Beat-switch second half", "mpc", "advanced", ["trap","experimental","dark-cinematic"],
    "Change the beat entirely halfway through for a dramatic two-part track.",
    "When you want a memorable structural surprise.",
    ["Build beat A for the first half", "Build a contrasting beat B", "Bridge them with a transition", "Keep one element to connect"],
    ["Change key at the switch", "Switch back for the finale", "Change BPM feel"]),
  opt("arrangement", "Loop-and-evolve (minimal change)", "mpc", "beginner", ["lofi","minimalist-drum-machine","boom-bap"],
    "Keep one loop running and evolve it subtly with small additions/automations.",
    "When you want a hypnotic, understated track.",
    ["Set the core loop", "Add one element every 8 bars", "Automate filters/effects for motion", "Remove elements near the end"],
    ["Add a single bridge variation", "Filter the whole loop down then up", "Introduce a fill every 16 bars"]),
  opt("arrangement", "Energy-curve mapping", "mpc", "intermediate", "all",
    "Plan each section's energy (1–5) so the track has a deliberate dynamic arc.",
    "When sections feel same-y or the track drags.",
    ["Assign an energy level to each section", "Ensure contrast (dips before peaks)", "Add/remove elements to hit targets", "Place the biggest moment ~2/3 through"],
    ["Add a false peak then a bigger one", "Dip to near-silence before the finale", "Map energy to the reference track"]),
  opt("arrangement", "Pre-hook lift section", "a4", "intermediate", ["southern-bounce","west-coast","trap"],
    "A short 2–4 bar pre-hook that builds anticipation before the chorus.",
    "When the jump from verse to hook feels too sudden.",
    ["Create a 2–4 bar pre-hook", "Add a riser or new chord", "Lift the energy slightly", "Land into the full hook"],
    ["Filter-sweep through the pre-hook", "Add a vocal chop", "Drop drums then slam the hook"]),
  opt("arrangement", "Drum-break breakdown", "rytm", "beginner", ["boom-bap","east-coast","west-coast","soul-sample"],
    "Strip to a drum break/solo for a few bars as a breakdown moment.",
    "When you want a classic head-nod breakdown.",
    ["Mute melodic parts for 2–4 bars", "Feature the drums (maybe a variation)", "Optionally add a scratch/vocal", "Rebuild into the next section"],
    ["Add a fill to exit", "Keep a filtered sample under it", "Half-time the break"]),
  opt("arrangement", "Outro fade / filter-down", "mpc", "beginner", "all",
    "End by filtering down and removing elements for a graceful outro.",
    "When you need a clean, satisfying ending.",
    ["Strip elements over the last 4–8 bars", "Automate a low-pass closing", "Leave a final element to fade", "End on a clean tail"],
    ["Loop a final chop to fade", "Tape-stop ending", "End cold on a hit"]),
  opt("arrangement", "AABA hook variation logic", "a4", "advanced", ["soul-sample","west-coast","experimental"],
    "Structure phrases as AABA so the hook varies its third statement for interest.",
    "When repeated hooks feel monotonous.",
    ["Write hook A", "Repeat A", "Write a contrasting B (bridge feel)", "Return to A varied"],
    ["Transpose the final A", "Add a counter-melody in the last A", "Extend B for a full bridge"]),
  opt("arrangement", "Section-length tuning by substyle", "mpc", "beginner", "all",
    "Set section lengths to match the substyle's norms (trap shorter, boom-bap looping).",
    "When you're unsure how long sections should be.",
    ["Check the substyle's arrangement tendencies", "Set intro/verse/hook lengths accordingly", "Keep trap hooks tight, lo-fi loops long", "A/B against a reference"],
    ["Halve a section for pace", "Double the final hook", "Add a tag after the outro"]),
  opt("arrangement", "Two-part dynamic (quiet → loud)", "mpc", "intermediate", ["dark-cinematic","experimental","lofi"],
    "Build the whole track from a quiet first half to a full, loud second half.",
    "When you want a cinematic, evolving dynamic.",
    ["Keep the first half sparse and quiet", "Gradually add elements", "Peak in the second half", "Use automation for the swell"],
    ["Add a sudden drop at the peak", "Pull back once before the climax", "Filter-open across the whole track"]),
  opt("arrangement", "Capture a live hardware jam, then edit", "mpc", "advanced", ["minimalist-drum-machine","experimental","west-coast"],
    "Perform a long live take across all devices into the MPC, then edit it into a song.",
    "When you want a spontaneous, human arrangement.",
    ["Set all devices syncing to the MPC clock", "Record a long live performance (mutes, fills, tweaks)", "Capture audio and/or MIDI", "Edit the best moments into a structure"],
    ["Comp two takes together", "Loop the best 8 bars as a base", "Keep happy accidents"]),
];

/* ---------------------------------------------------------- AUTOMATION */
const automation: CreativeOption[] = [
  opt("automation", "Live mute performance capture", "mpc", "beginner", "all",
    "Record a live performance of track mutes to arrange the song with human feel.",
    "When you want a performed, dynamic arrangement.",
    ["Build a full pattern", "Arm the MPC to record mutes", "Perform the arrangement live (intro→outro)", "Keep the best take"],
    ["Layer two mute takes", "Automate a filter while muting", "Punch in fixes on weak spots"]),
  opt("automation", "Slow filter open across a verse", "a4", "beginner", "all",
    "Automate a filter slowly opening over 8–16 bars for a gradual energy lift.",
    "When sections feel static.",
    ["Pick the element (chords/sample/bus)", "Automate the filter low→high over the section", "Add resonance for character", "Reset for the next loop"],
    ["Open into the hook only", "LFO under the automation", "Close it for the outro"]),
  opt("automation", "Rytm performance-macro fills", "rytm", "intermediate", ["trap","minimalist-drum-machine","experimental"],
    "Use the Rytm performance macros for live snare delay throws, kick decay, filter sweeps.",
    "When you want expressive, hands-on drum variation.",
    ["Assign performance macros on the Rytm", "Map them to useful params (decay, delay send, filter)", "Perform them at transitions/fills", "Record the result into the MPC"],
    ["Throw a snare delay at phrase ends", "Sweep the hat filter live", "Crush the kick momentarily"]),
  opt("automation", "A4 parameter-lock evolution", "a4", "intermediate", ["experimental","minimalist-drum-machine","dark-cinematic"],
    "Use p-locks so the synth evolves note-to-note across the pattern.",
    "When a synth part feels static.",
    ["Program the A4 part", "P-lock filter/env/pitch on select steps", "Let the part morph each bar", "Record long passes for variation"],
    ["P-lock the FX send on accents", "Randomize a few locks", "Change locks per section"]),
  opt("automation", "Tempo-synced LFO wobble", "a4", "beginner", ["trap","experimental","lofi","grimy-underground"],
    "Add a tempo-synced LFO to filter/pitch/amp for rhythmic movement.",
    "When you want hands-off rhythmic motion.",
    ["Pick the target (filter, pitch, amp)", "Set the A4 LFO synced to tempo", "Choose rate (1/4, 1/8, 1/16)", "Set depth to taste"],
    ["Change LFO shape (sine vs square)", "Speed the LFO into the drop", "Apply to the bass for wobble"]),
  opt("automation", "Volume-swell pad automation", "a4", "beginner", ["dark-cinematic","lofi","experimental"],
    "Automate a pad swelling in and out for breathing atmosphere.",
    "When a pad sits too statically.",
    ["Build a pad on the A4", "Automate its volume to swell each phrase", "Time swells to section starts", "Keep it subtle"],
    ["Swell into every hook", "Add filter movement with the swell", "Crossfade two pads"]),
  opt("automation", "Send-level automation (reverb/delay)", "mpc", "intermediate", "all",
    "Automate FX send levels to add space/movement at key moments.",
    "When the FX should breathe with the arrangement.",
    ["Set a reverb/delay send", "Automate the send up in breakdowns", "Pull it back in dense sections", "Time changes to the arrangement"],
    ["Throw a send spike on phrase ends", "Automate delay feedback", "Open the send for the outro"]),
  opt("automation", "Panning automation movement", "any", "intermediate", ["experimental","west-coast","lofi"],
    "Automate panning of an element for stereo motion and interest.",
    "When the stereo image feels static.",
    ["Pick a non-bass element", "Automate slow pan moves", "Keep lows centered", "Time moves musically"],
    ["Ping-pong an element", "Auto-pan synced to tempo", "Widen into the hook"]),
  opt("automation", "Drum density automation", "rytm", "intermediate", "all",
    "Vary drum density over the arrangement (sparse verse, busy hook) via mutes/p-locks.",
    "When drums feel the same throughout.",
    ["Program a busy full pattern", "Mute elements for sparse sections", "Unmute for busy sections", "Automate the changes in the MPC"],
    ["Add hat rolls only in hooks", "Drop the kick in a breakdown", "Double-time hats into the drop"]),
  opt("automation", "Pitch-rise automation into drop", "a4", "intermediate", ["trap","dark-cinematic","southern-bounce"],
    "Automate a pitch rise on a synth/noise to build tension into a drop.",
    "When you want a rising-tension transition.",
    ["Pick a synth/noise on the A4", "Automate pitch up over the build", "Combine with a filter open", "Cut/resolve at the drop"],
    ["Add a riser layer", "Pitch the whole mix up briefly", "Reverse-tail into the drop"]),
  opt("automation", "Resonance sweep accents", "a4", "advanced", ["experimental","minimalist-drum-machine","grimy-underground"],
    "Automate filter resonance up for screaming accents at key moments.",
    "When you want aggressive, attention-grabbing motion.",
    ["Set the A4 filter with resonance", "Automate resonance up on accents", "Watch levels (resonance can spike)", "Use sparingly for impact"],
    ["Self-oscillate for a tone", "Sweep resonance + cutoff together", "Automate per section"]),
  opt("automation", "Distortion/drive automation", "rytm", "intermediate", ["grimy-underground","trap","dark-cinematic"],
    "Automate analog drive/distortion to intensify sections.",
    "When you want sections to get progressively grittier.",
    ["Set drive on the Rytm/A4", "Automate it up toward the climax", "Compensate level", "Pull back for contrast"],
    ["Drive only in the final hook", "Bitcrush automation", "Drive the bus for a section"]),
  opt("automation", "Stutter/retrig performance", "rytm", "advanced", ["experimental","trap","grimy-underground"],
    "Perform live retriggers/stutters on the Rytm or MPC as fills and accents.",
    "When you want spontaneous, glitchy variation.",
    ["Set up retrig on the Rytm or note-repeat on MPC", "Perform it at phrase ends", "Vary the rate for builds", "Record the performance"],
    ["Pitch-ramp the retrig", "Stutter a vocal chop", "Gate the stutter"]),
  opt("automation", "Crossfade between pattern variations", "mpc", "advanced", ["minimalist-drum-machine","experimental","west-coast"],
    "Smoothly transition between A/B Elektron patterns by recording the crossover live.",
    "When you want organic evolution between variations.",
    ["Create A and B patterns on an Elektron", "Switch between them while recording into the MPC", "Use a fill/transition to mask the switch", "Capture the live change"],
    ["Morph params during the switch", "Layer both briefly", "Automate a filter over the switch"]),
  opt("automation", "Automated breakdown + rebuild", "mpc", "intermediate", "all",
    "Automate a full breakdown (elements out, filter down) and a rebuild.",
    "When you want a dynamic dip without manual muting each time.",
    ["Automate elements muting into the breakdown", "Automate a filter closing", "Rebuild elements one at a time", "Open the filter into the next section"],
    ["Add a riser on the rebuild", "Leave only bass in the dip", "Add a new element on rebuild"]),
];

/* ------------------------------------------------------------- MIX PREP */
const mixprep: CreativeOption[] = [
  opt("mixprep", "Gain-stage every element first", "mpc", "beginner", "all",
    "Set healthy, consistent levels before any processing so the mix starts clean.",
    "When you're about to start mixing or prepping stems.",
    ["Bring all faders down", "Set the loudest element to a healthy level", "Balance others against it", "Leave master headroom (~-6 dB)"],
    ["Gain-stage to a reference track", "Group similar elements first", "Check the master meter for peaks"]),
  opt("mixprep", "Mix at low volume", "mpc", "beginner", "all",
    "Balance the rough mix quietly; if it works soft, it translates loud.",
    "When you want a balanced mix that translates.",
    ["Turn the monitors down low", "Balance the core elements first", "Add detail elements last", "Check translation on phone speakers"],
    ["A/B at two volumes", "Mono-check the balance", "Reference a commercial track quietly"]),
  opt("mixprep", "Carve the low-end (kick vs. bass)", "a4", "intermediate", "all",
    "Make sure the kick and bass each own their space in the low end.",
    "When the low end is muddy or weak.",
    ["Decide who owns the sub (usually 808/bass)", "High-pass the kick slightly OR the bass", "Sidechain the bass to the kick", "Check on a sub speaker/headphones"],
    ["EQ a notch in the bass for the kick", "Mono the lows", "Pick complementary kick/bass tunings"]),
  opt("mixprep", "High-pass non-bass elements", "mpc", "beginner", "all",
    "Remove unnecessary low frequencies from everything except the bass/kick.",
    "When the mix is cluttered or muddy in the lows.",
    ["High-pass pads/leads/hats/samples", "Set each HPF by ear (remove rumble only)", "Keep the bass/kick full-range", "Recheck the low-end clarity"],
    ["Steeper HPF for busy mixes", "Automate HPF in dense sections", "HPF the reverb returns"]),
  opt("mixprep", "Reference-track A/B comparison", "mpc", "beginner", "all",
    "Compare your mix to a professional reference for tonal and level balance.",
    "When you're unsure if the mix is balanced.",
    ["Import a reference on a muted track", "Match its loudness for fair comparison", "A/B tonal balance (lows/mids/highs)", "Adjust toward (not copying) the reference"],
    ["Use a spectrum analyzer to compare", "A/B the low-end weight", "Check stereo width vs reference"]),
  opt("mixprep", "Pan for width and clarity", "mpc", "beginner", "all",
    "Spread elements across the stereo field so each is heard clearly.",
    "When elements mask each other in the center.",
    ["Keep kick/snare/bass centered", "Pan hats/percussion slightly off", "Pan ear candy wide", "Balance left/right energy"],
    ["Mirror-pan doubled elements", "Widen the pad with stereo FX", "Mono-check for phase issues"]),
  opt("mixprep", "Bus / glue compression", "mpc", "intermediate", "all",
    "Light bus compression to glue the mix together.",
    "When the mix feels disjointed.",
    ["Add a compressor on the mix bus", "Use gentle settings (2:1, slow attack)", "Aim for 1–2 dB gain reduction", "Listen for cohesion, not pumping"],
    ["Parallel-compress the drums", "Glue the drum bus separately", "Add make-up gain carefully"]),
  opt("mixprep", "Resample/print FX to commit", "mpc", "intermediate", ["lofi","experimental","boom-bap","grimy-underground"],
    "Resample processed elements to commit the sound and simplify the mix.",
    "When you have heavy processing you're happy with.",
    ["Solo and record the processed element", "Save it as a new sample", "Replace the live-processed version", "Free up CPU/effects"],
    ["Keep a dry backup", "Resample the whole drum bus", "Print the master FX chain"]),
  opt("mixprep", "Tame harsh resonances", "a4", "intermediate", "all",
    "Find and reduce harsh frequency peaks for a smoother mix.",
    "When something sounds harsh or fatiguing.",
    ["Sweep a narrow EQ boost to find harshness", "Cut that frequency", "Check synths/cymbals/samples especially", "A/B to confirm improvement"],
    ["Dynamic-EQ the harsh band", "De-ess bright samples", "Tame A4 filter resonance"]),
  opt("mixprep", "Set up stems / individual outs", "rytm", "intermediate", "all",
    "Route drums/bass/melody to separate outputs for clean stem capture.",
    "When prepping for external mixing or stem export.",
    ["Decide stem groups (drums/bass/harmony/melody/texture)", "Route each to its own output/track", "Record each cleanly into the MPC", "Label consistently"],
    ["Use Rytm individual outs for drum stems", "Print dry + wet stems", "Group sub-mixes for fewer stems"]),
  opt("mixprep", "Check mono compatibility", "mpc", "beginner", "all",
    "Sum the mix to mono to catch phase cancellation and balance issues.",
    "When you've used wide stereo effects.",
    ["Sum the master to mono", "Listen for elements disappearing", "Fix phase issues on wide elements", "Keep the lows mono"],
    ["Mono-check each section", "Narrow problematic wide elements", "Re-pan after mono-checking"]),
  opt("mixprep", "Sidechain pad/sample to the kick", "any", "intermediate", ["trap","dark-cinematic","west-coast","southern-bounce"],
    "Duck sustained elements to the kick for a punchy, clear mix.",
    "When the kick gets buried by pads/samples.",
    ["Sidechain the pad/sample to the kick", "Set gentle ducking", "Tune the release musically", "Confirm the kick punches through"],
    ["Subtle duck for transparency", "Pump for an obvious effect", "Sidechain the reverb too"]),
  opt("mixprep", "Headroom & master-bus prep", "mpc", "beginner", "all",
    "Leave proper headroom on the master so mastering has room to work.",
    "When prepping the final export.",
    ["Aim for master peaks around -6 dB", "Remove any limiter for stem export", "Leave a light limiter only for a reference mix", "Check no clipping anywhere"],
    ["Print a -6 dB and a louder reference", "Leave the master clean for stems", "Note target loudness"]),
  opt("mixprep", "Write recall / session notes", "mpc", "beginner", "all",
    "Document BPM, key, kits, patches, and routing for future recall.",
    "When finishing a session you may return to.",
    ["Note BPM, key, swing", "List Rytm kit and A4 patches used", "Note MIDI routing and levels", "Save with the project files"],
    ["Photo the hardware settings", "Export a settings text file", "Note unfinished ideas for later"]),
  opt("mixprep", "Balance check on multiple speakers", "mpc", "beginner", "all",
    "Audition the rough mix on phone, laptop, earbuds, and monitors.",
    "When confirming the mix translates before export.",
    ["Bounce a rough mix", "Play it on phone speakers", "Check laptop + earbuds", "Note what changes and adjust"],
    ["Check in the car", "A/B on each system vs reference", "Fix the worst-translating element"]),
];

export const CREATIVE_OPTIONS: CreativeOption[] = [
  ...drums, ...bass, ...chords, ...melody, ...samples, ...texture,
  ...effects, ...transition, ...arrangement, ...automation, ...mixprep,
];

export function optionsByCategory(category: CreativeCategory): CreativeOption[] {
  return CREATIVE_OPTIONS.filter((o) => o.category === category);
}
