import type { HipHopSubstyle, SubstyleId } from "./types";

/**
 * Substyle library. BPM ranges and characteristics are production-oriented
 * generalizations meant to guide creative choices, not hard rules.
 */
export const SUBSTYLES: HipHopSubstyle[] = [
  {
    id: "boom-bap",
    name: "Boom Bap",
    blurb: "Dusty, sample-driven, hard-swung drums. Classic 90s head-nod.",
    bpmRange: [82, 95],
    grooveFeel: "Heavy swing, slightly behind the beat, human timing.",
    drums: "Punchy kick, cracking snare on 2 & 4, swung 16th hats, vinyl dust.",
    bass: "Walking or simple root-driven upright/sub bass locked to the kick.",
    harmony: "Chopped soul/jazz samples, minor 7th & 9th colors, filtered loops.",
    effects: "Saturation, bitcrush, vinyl sim, tape, light room reverb.",
    arrangement: "Loop-based, 4/8/16-bar sections, scratch hooks, drum-only breaks.",
    deviceSuggestions: {
      mpc: "Chop the sample, build the swing, arrange sections, master clock.",
      rytm: "Layer an acoustic-style kick/snare under the sample drums; add ghost snares.",
      a4: "Add a sub-bass reinforcement or a filtered Rhodes-style stab.",
    },
    defaultSwing: 58,
  },
  {
    id: "trap",
    name: "Trap",
    blurb: "Booming 808s, rolling hats, triplet feel, cinematic space.",
    bpmRange: [130, 160],
    grooveFeel: "Half-time feel; often written/felt at half the BPM.",
    drums: "Tuned 808 kick, snappy clap/snare on 3, fast hat rolls & triplets.",
    bass: "Pitched 808 glides following the key; long sustained sub notes.",
    harmony: "Dark minor melodies, bells, plucks, sparse eerie pads.",
    effects: "Long reverb tails, pitch glides, stutter edits, distortion on 808.",
    arrangement: "Intro, hook-first structures, beat switches, hat-roll build-ups.",
    deviceSuggestions: {
      mpc: "Program hat rolls and ratchets, arrange beat switches, master clock.",
      rytm: "Design the snappy clap/snare and hi-hat texture; performance ratchets.",
      a4: "Build the pitched 808/sub-bass with glide; dark bell/pluck leads.",
    },
    defaultSwing: 51,
  },
  {
    id: "lofi",
    name: "Lo-Fi Hip-Hop",
    blurb: "Warm, hazy, mellow. Imperfect timing and cozy texture.",
    bpmRange: [70, 90],
    grooveFeel: "Loose swing, intentional timing drift, relaxed pocket.",
    drums: "Soft dusty kick, brushed snare, quiet hats, lots of swing & wobble.",
    bass: "Round, soft upright/electric bass, simple and warm.",
    harmony: "Jazzy 7th/9th chords, detuned Rhodes, vinyl crackle, mellow keys.",
    effects: "Tape wow/flutter, vinyl noise, low-pass filtering, bit reduction.",
    arrangement: "Short loops, minimal changes, ambient intros, found-sound interludes.",
    deviceSuggestions: {
      mpc: "Add timing humanization, vinyl sim, low-pass; keep loops simple.",
      rytm: "Soften drums with low velocities, add brush/rim textures, detune.",
      a4: "Detuned Rhodes/keys, soft analog bass, slow filter movement.",
    },
    defaultSwing: 60,
  },
  {
    id: "experimental",
    name: "Experimental Hip-Hop",
    blurb: "Abstract, glitchy, rule-breaking. Texture over convention.",
    bpmRange: [60, 110],
    grooveFeel: "Off-grid, polymetric, unstable or shifting groove.",
    drums: "Broken/glitched patterns, odd time, granular hits, found percussion.",
    bass: "Distorted, modulated, or atonal sub movement.",
    harmony: "Dissonant clusters, microtonal bends, sampled noise, reversed tones.",
    effects: "Granular, bitcrush, extreme modulation, resampling, feedback.",
    arrangement: "Non-repeating, collage-like, abrupt cuts, evolving textures.",
    deviceSuggestions: {
      mpc: "Resample everything, chop chaotically, automate plugin params.",
      rytm: "Heavy parameter locks, retrigs, sample mangling on the drum voices.",
      a4: "Aggressive LFO/env modulation, FM-ish tones, atonal sweeps.",
    },
    defaultSwing: 50,
  },
  {
    id: "dark-cinematic",
    name: "Dark Cinematic",
    blurb: "Moody, filmic, tense. Wide space and ominous tone.",
    bpmRange: [75, 100],
    grooveFeel: "Patient, deliberate, often half-time and spacious.",
    drums: "Impactful kicks, reverbed snares, sparse but huge hits.",
    bass: "Deep sustained sub, slow swells, menacing low drones.",
    harmony: "Minor strings/choir samples, dissonant pads, single-note motifs.",
    effects: "Huge reverbs, risers, sub drops, distortion, reverse swells.",
    arrangement: "Tension/release, long builds, dynamic drops, score-like dynamics.",
    deviceSuggestions: {
      mpc: "Arrange dynamic builds, automate filters/reverb sends, master clock.",
      rytm: "Cinematic impact hits, reverse cymbals, deep toms, sparse placement.",
      a4: "Drones, slow pad swells, dark single-note motifs, sub reinforcement.",
    },
    defaultSwing: 52,
  },
  {
    id: "west-coast",
    name: "West Coast",
    blurb: "G-funk lean: bouncy, melodic synth leads, smooth low end.",
    bpmRange: [90, 105],
    grooveFeel: "Laid-back bounce, slight swing, confident pocket.",
    drums: "Tight punchy kick/snare, clean hats, occasional talkbox-era claps.",
    bass: "Smooth synth bass, melodic and groovy, follows the chords.",
    harmony: "High portamento lead synths, warm minor chords, funky stabs.",
    effects: "Portamento/glide, light chorus, smooth filtering, clean delay.",
    arrangement: "Verse/hook with strong melodic hooks, breakdowns, vocal space.",
    deviceSuggestions: {
      mpc: "Sequence the bounce, arrange hooks, keep drums tight, master clock.",
      rytm: "Tight analog kick/snare, crisp hats, clean and punchy.",
      a4: "Signature whiny portamento lead + smooth synth bass; funky stabs.",
    },
    defaultSwing: 55,
  },
  {
    id: "east-coast",
    name: "East Coast",
    blurb: "Gritty, lyrical, sample-forward, hard drums and dark loops.",
    bpmRange: [85, 95],
    grooveFeel: "Hard swing, aggressive pocket, head-nod authority.",
    drums: "Hard-hitting kick/snare, tight swung hats, dusty breaks.",
    bass: "Dark sub locked to kick, sometimes sampled bassline.",
    harmony: "Dark jazz/soul chops, minor & diminished colors, eerie loops.",
    effects: "Saturation, filtering, vinyl sim, tight delay throws.",
    arrangement: "Loop-driven verses, scratch hooks, drum breaks, hard intros.",
    deviceSuggestions: {
      mpc: "Chop dark loops, hard swing, arrange verses + breaks, master clock.",
      rytm: "Reinforce the break with punchy analog drums + ghost notes.",
      a4: "Sub reinforcement, occasional dark stab or filtered key.",
    },
    defaultSwing: 57,
  },
  {
    id: "southern-bounce",
    name: "Southern Bounce",
    blurb: "Energetic, chant-friendly, syncopated, club-ready.",
    bpmRange: [95, 145],
    grooveFeel: "Bouncy syncopation, call-and-response energy.",
    drums: "Snappy claps, syncopated kicks, lively hats, hand-clap layers.",
    bass: "Punchy synth/808 bass with bounce, syncopated rhythm.",
    harmony: "Catchy simple riffs, organ/brass stabs, chantable motifs.",
    effects: "Filter sweeps, claps with verb, vocal chop fx, risers.",
    arrangement: "Chant hooks, call-and-response, energetic drops, breakdowns.",
    deviceSuggestions: {
      mpc: "Sequence the bounce + chant chops, arrange drops, master clock.",
      rytm: "Layered claps, syncopated kick programming, lively hat performance.",
      a4: "Punchy bass with bounce, organ/brass-style stabs, catchy riffs.",
    },
    defaultSwing: 54,
  },
  {
    id: "grimy-underground",
    name: "Grimy Underground",
    blurb: "Raw, lo-fi, aggressive, intentionally rough and dark.",
    bpmRange: [80, 95],
    grooveFeel: "Hard, slightly sloppy on purpose, raw energy.",
    drums: "Overdriven kick/snare, crunchy hats, distorted breaks.",
    bass: "Distorted sub, gnarly and forward in the mix.",
    harmony: "Detuned dark samples, horror-movie motifs, dissonance.",
    effects: "Heavy distortion, bitcrush, aggressive filtering, noise.",
    arrangement: "Loop-heavy, abrupt, raw intros, minimal polish.",
    deviceSuggestions: {
      mpc: "Resample to degrade, overdrive the bus, hard chops, master clock.",
      rytm: "Push the analog drive, distort the drums, gritty parameter locks.",
      a4: "Distorted sub, detuned dark motifs, overdriven filter resonance.",
    },
    defaultSwing: 56,
  },
  {
    id: "soul-sample",
    name: "Soul Sample-Based",
    blurb: "Emotive chopped soul/gospel, pitched vocals, warm and rich.",
    bpmRange: [85, 100],
    grooveFeel: "Warm swing, soulful pocket, head-nod groove.",
    drums: "Warm punchy drums supporting the sample, tasteful swing.",
    bass: "Fingered/upright-style bass following the sample chords.",
    harmony: "Chopped soul vocals & instrumentation, lush extended chords.",
    effects: "Pitch shifting, time-stretch, filtering, tape warmth, sidechain.",
    arrangement: "Sample flips, vocal chop hooks, filtered intros, verse drops.",
    deviceSuggestions: {
      mpc: "Chop & pitch the soul sample, time-stretch, arrange, master clock.",
      rytm: "Warm supportive drums tuned to the sample's key feel.",
      a4: "Bass that follows the sample harmony; subtle pad to glue chops.",
    },
    defaultSwing: 57,
  },
  {
    id: "minimalist-drum-machine",
    name: "Minimalist Drum-Machine",
    blurb: "Sparse, hardware-purist, groove-and-space focused.",
    bpmRange: [85, 110],
    grooveFeel: "Tight machine groove with deliberate space and dynamics.",
    drums: "Pure drum-machine voices, sparse arrangement, strong groove.",
    bass: "Single analog bass line, repetitive and hypnotic.",
    harmony: "One or two synth elements, motif-driven, lots of space.",
    effects: "Subtle delay, light reverb, analog character, tasteful filtering.",
    arrangement: "Subtractive — mute/unmute elements, long evolving sections.",
    deviceSuggestions: {
      mpc: "Arrange via mutes, capture performance, minimal layering, master clock.",
      rytm: "The star: craft every analog drum voice, perform mutes & p-locks.",
      a4: "One hypnotic bass + one motif; slow parameter evolution.",
    },
    defaultSwing: 53,
  },
];

export const SUBSTYLE_MAP: Record<SubstyleId, HipHopSubstyle> = Object.fromEntries(
  SUBSTYLES.map((s) => [s.id, s])
) as Record<SubstyleId, HipHopSubstyle>;

export function getSubstyle(id: SubstyleId): HipHopSubstyle {
  return SUBSTYLE_MAP[id] ?? SUBSTYLES[0];
}
